language: rust
rust:
  - nightly
  - 1.0.0-beta.2
os:
  - linux
  - osx
env:
  global:
    - secure: dQm6A7+yuwJTXrnZehIhCSX0NS9amJ8EZE6e2cD4KMKhxqoThsSuKBWmMrb3iT9l3fYhgFakc/W6jdSrsmglmcUUqdmUNCnDSB5q3Nb9cThYT6F7Ueyxl7n8Hz1RiuEl7qef/Ze45Ej481L86dctWWblB/hcywh6d+hTR0+r0O8=
    - secure: "MvCGPnHryMhBTgqLo7ehOhT3VNkioqBpk/LmH+Zsbs5zrdjZlOkoegq1RbzaT0O5pjlCPDi/GzmCHDwXK5geKJ99spN6BFj/NL99/+f/KKGwzsiRtJg64daEjbxMqJeUzllXd4frDEfunZthziU1vVVWsaScG7IGyFk2QH1d1CY="
script:
  - sh scripts/cargo.sh build -v
  - sh scripts/cargo.sh test -v
  - sh scripts/cargo.sh doc --no-deps
after_success:
  - mv target/doc doc
  - bash upload_doc.sh