language: rust
rust:
  - nightly
  - beta
os:
  - linux
  - osx
script:
  - sh scripts/cargo.sh build -v
  - sh scripts/cargo.sh test -v
  - sh scripts/cargo.sh doc --no-deps
after_success:
  - sh scripts/upload_doc.sh