language: rust
sudo: false
cache:
  directories:
    - $HOME/.cargo
rust:
  - 1.0.0
os:
  - linux
  - osx
branches:
  only:
    - master
    - auto
script:
  - cargo build -v --features strict
  - cargo build -v --no-default-features --features strict
  - cargo test -v --features strict
  - cargo doc
after_success:
  - sh scripts/upload_doc.sh