version: '{branch}-{build}'
skip_tags: true
platform: x64
os: MinGW
environment:
  RUST_INSTALL_DIR: C:\Rust
  RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
  RUST_VERSION: 1.0.0
  OPENSSL_EXE: Win32OpenSSL-1_0_2d.exe
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-$Env:RUST_VERSION-$Env:RUST_INSTALL_TRIPLE.exe"
  - cmd: rust-%RUST_VERSION%-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /COMPONENTS="rust,gcc,cargo" /DIR="%RUST_INSTALL_DIR%"
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin;C:\MINGW\bin\
  - rustc --version
  - cargo --version
  - ps: Start-FileDownload "http://slproweb.com/download/$Env:OPENSSL_EXE"
  - cmd: %OPENSSL_EXE /silent /verysilent /sp- /suppressmsgboxes
  - cmd: SET OPENSSL_LIB_DIR=C:\OpenSSL-Win32
  - cmd: SET OPENSSL_INCLUDE_DIR=C:\OpenSSL-Win32\include
build: false
test_script:
  - cargo build -v
  - cargo build -v --no-default-features
  - cargo test --lib -v