[package]

name = "rustful"
version = "0.1.0-pre"
authors = ["hello@erikhedvall.nu"]

[lib]

name = "rustful"
path = "src/lib.rs"

[features]
#this will be default as long as it's the only alternative
default = ["nightly"]
nightly = ["hyper/nightly"]

[dependencies]
hyper = "*"
time = "*"
url = "*"
anymap = "*"

[dev-dependencies]
tempdir = "*"
