[package]

name = "rustful"
version = "0.1.0-pre"
authors = ["hello@erikhedvall.nu"]

[lib]

name = "rustful"
path = "src/lib.rs"

[features]
default = ["macros"]
macros = ["rustful_macros"]

[dependencies.rustful_macros]
path = "macros"
optional = true

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"

[dependencies.time]
git = "https://github.com/rust-lang/time"