[package]

name = "rustful"
version = "0.1.0-pre"
authors = ["hello@erikhedvall.nu"]

[lib]

name = "rustful"
path = "src/lib.rs"

[dependencies]
hyper = "*"
time = "*"
url = "*"

[dev-dependencies]
tempdir = "*"
