[package]

name = "rustful"
version = "0.1.0-pre"
authors = ["hello@erikhedvall.nu"]

[lib]

name = "rustful"
path = "src/lib.rs"

[features]
default = ["macros"]
ssl = ["http/ssl"]
macros = ["rustful_macros"]

[dependencies.rustful_macros]
path = "macros"
optional = true

[dependencies.http]
git = "https://github.com/chris-morgan/rust-http"
default-features = false

[dependencies.time]
git = "https://github.com/rust-lang/time"